# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='用户头像'),
        ),
    ]
